catbook/config/routes.rb
Rails.application.routes.draw do
  resources :posts

  resources :postnames

  resources :users

end

catbook/app/models/post.rb
class Post < ActiveRecord::Base
end

catbook/app/models/postname.rb
class Postname < ActiveRecord::Base
end

catbook/app/models/user.rb
class User < ActiveRecord::Base
end

catbook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

catbook/app/controllers/postnames_controller.rb
class PostnamesController < ApplicationController
  before_action :set_postname, only: [:show, :edit, :update, :destroy]

  # GET /postnames
  # GET /postnames.json
  def index
    @postnames = Postname.all
  end

  # GET /postnames/1
  # GET /postnames/1.json
  def show
  end

  # GET /postnames/new
  def new
    @postname = Postname.new
  end

  # GET /postnames/1/edit
  def edit
  end

  # POST /postnames
  # POST /postnames.json
  def create
    @postname = Postname.new(postname_params)

    respond_to do |format|
      if @postname.save
        format.html { redirect_to @postname, notice: 'Postname was successfully created.' }
        format.json { render :show, status: :created, location: @postname }
      else
        format.html { render :new }
        format.json { render json: @postname.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postnames/1
  # PATCH/PUT /postnames/1.json
  def update
    respond_to do |format|
      if @postname.update(postname_params)
        format.html { redirect_to @postname, notice: 'Postname was successfully updated.' }
        format.json { render :show, status: :ok, location: @postname }
      else
        format.html { render :edit }
        format.json { render json: @postname.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postnames/1
  # DELETE /postnames/1.json
  def destroy
    @postname.destroy
    respond_to do |format|
      format.html { redirect_to postnames_url, notice: 'Postname was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_postname
      @postname = Postname.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def postname_params
      params.require(:postname).permit(:name, :body)
    end
end

catbook/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:handle, :body)
    end
end

catbook/app/controllers/users_controller.rb
#This class defines methods that are used by the User resource. The user views rely on this file for instance variables/methods

class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

catbook/app/helpers/application_helper.rb
module ApplicationHelper
end

catbook/app/helpers/postnames_helper.rb
module PostnamesHelper
end

catbook/app/helpers/posts_helper.rb
module PostsHelper
end

catbook/app/helpers/users_helper.rb
module UsersHelper
end

catbook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

catbook/app/views/postnames/_form.html.erb
<%= form_for(@postname) do |f| %>
  <% if @postname.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@postname.errors.count, "error") %> prohibited this postname from being saved:</h2>

      <ul>
      <% @postname.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

catbook/app/views/postnames/edit.html.erb
<h1>Editing postname</h1>

<%= render 'form' %>

<%= link_to 'Show', @postname %> |
<%= link_to 'Back', postnames_path %>

catbook/app/views/postnames/index.html.erb
<h1>Listing postnames</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @postnames.each do |postname| %>
      <tr>
        <td><%= postname.name %></td>
        <td><%= postname.body %></td>
        <td><%= link_to 'Show', postname %></td>
        <td><%= link_to 'Edit', edit_postname_path(postname) %></td>
        <td><%= link_to 'Destroy', postname, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Postname', new_postname_path %>

catbook/app/views/postnames/new.html.erb
<h1>New postname</h1>

<%= render 'form' %>

<%= link_to 'Back', postnames_path %>

catbook/app/views/postnames/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @postname.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @postname.body %>
</p>

<%= link_to 'Edit', edit_postname_path(@postname) %> |
<%= link_to 'Back', postnames_path %>

catbook/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

catbook/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

catbook/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

catbook/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

catbook/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>